### PR TITLE
package and release artifacts

### PR DESCRIPTION
**Pull request by itskarthig**

### CODE REVIEW

**Comment by madninja** [comment]
I'd like this to mirror the gateway-rs repo more in that it would also have a CI stage that builds and does a clippy pass for every PR/master commit

**Comment by itskarthig** [comment]
Ok. Will update the PR.

**Comment by shawaj** [comment]
Should probably add builds for all of the build targets listed here also? https://github.com/helium/gateway-rs#supported-platforms

**Comment by madninja** [comment]
Closing in favor of #9

**Pull request closed without merging**
