### PR TITLE
feat: add all build targets from gateway-rs

### PR DESCRIPTION
**Pull request by shawaj**
Add all build targets currently supported for gateway-rs

List from https://github.com/helium/gateway-rs#supported-platforms

Related to #9

### CODE REVIEW

**Comment by madninja** [comment]
Sorta weird to add targets that we know currently don't have an ecc or equivalent attached to it, which is why I left them out, but adding these targets doesn't hurt

**Comment by shawaj** [comment]
@madninja ahh yeah that's a good point and something I completely didn't think about. 

I guess some vendors may update their hardware to add ECC? But happy to remove any if not sure? I guess github actions are free of charge on open repos so as you say not a big deal... But perhaps slows down the build?

Other thing is, we could add "ECC on board" column on the table in gateway-rs and a note to amend the build here if it contains one? Happy to write something like that up if you think it's worthwhile?

**Comment by shawaj** [comment]
@madninja any chance you could do a `v0.1.7-beta` tagged released or something similar so the armv6 build will trigger? Or maybe just delete and retag/release for v0.1.6?

**Comment by madninja** [comment]
Tagged 0.1.7

**Comment by shawaj** [comment]
> Tagged 0.1.7

Thanks very much @madninja much appreciated :-)

**Pull request merged**
